# GitHub Action updates the requirements_for_dependabot.txt file (if needed) when doing a git push
name: requirements_for_dependabot_txt
on: [push]
jobs:
  requirements_for_dependabot_txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: mkdir temp
      - run: cp site-packages/pip.py temp/pip.py
      - name: requirements_for_dependabot_txt
        shell: python
        run: |
            from temp.pip.py import BUNDLED_MODULES
            print("\n".join(sorted(set(BUNDLED_MODULES))))
